var startingPosition = `{
    "positions":{
        "quantity":32, 
        "pieces":[
                {
                "position":"A_1",
                "name":"white_rook"
            },
            {
                "position":"A_2",
                "name":"white_pawn"
            },
            {
                "position":"A_7",
                "name":"black_pawn"
            },
            {
                "position":"A_8",
                "name":"black_rook"
            },
            {
                "position":"B_1",
                "name":"white_knight"
            },
            {
                "position":"B_2",
                "name":"white_pawn"
            },
            {
                "position":"B_7",
                "name":"black_pawn"
            },
            {
                "position":"B_8",
                "name":"black_knight"
            },
            {
                "position":"C_1",
                "name":"white_bishop"
            },
            {
                "position":"C_2",
                "name":"white_pawn"
            },
            {
                "position":"C_7",
                "name":"black_pawn"
            },
            {
                "position":"C_8",
                "name":"black_bishop"
            },
            {
                "position":"D_1",
                "name":"white_queen"
            },
            {
                "position":"D_2",
                "name":"white_pawn"
            },
            {
                "position":"D_7",
                "name":"black_pawn"
            },
            {
                "position":"D_8",
                "name":"black_queen"
            },
            {
                "position":"E_1",
                "name":"white_king"
            },
            {
                "position":"E_2",
                "name":"white_pawn"
            },
            {
                "position":"E_7",
                "name":"black_pawn"
            },
            {
                "position":"E_8",
                "name":"black_king"
            },
            {
                "position":"F_1",
                "name":"white_bishop"
            },
            {
                "position":"F_2",
                "name":"white_pawn"
            },
            {
                "position":"F_7",
                "name":"black_pawn"
            },
            {
                "position":"F_8",
                "name":"black_bishop"
            },
            {
                "position":"G_1",
                "name":"white_knight"
            },
            {
                "position":"G_2",
                "name":"white_pawn"
            },
            {
                "position":"G_7",
                "name":"black_pawn"
            },
            {
                "position":"G_8",
                "name":"black_knight"
            },
            {
                "position":"H_1",
                "name":"white_rook"
            },
            {
                "position":"H_2",
                "name":"white_pawn"
            },
            {
                "position":"H_7",
                "name":"black_pawn"
            },
            {
                "position":"H_8",
                "name":"black_rook"
            }
        ] 
    }    
}`;
